
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_quote
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quote_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
